# Generated by Django 3.1.7 on 2021-06-01 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
