# Generated by Django 3.1.7 on 2021-06-02 06:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210602_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.ImageField(upload_to=accounts.models.unique_file_path),
        ),
    ]
