# Generated by Django 3.1.7 on 2021-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210602_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
