# Generated by Django 3.1.7 on 2021-06-02 06:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210602_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_upload',
            field=models.FileField(upload_to=accounts.models.unique_file_path),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.FileField(upload_to=accounts.models.unique_file_path),
        ),
    ]
