# Generated by Django 3.1.7 on 2021-06-02 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210602_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Arquivo'),
        ),
    ]
