# Generated by Django 3.1.7 on 2021-06-02 09:55

import accounts.models
import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210602_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_upload',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=accounts.models.unique_file_path),
        ),
    ]
