# Generated by Django 3.1.7 on 2021-06-02 10:03

import accounts.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210602_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_upload',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=accounts.models.unique_file_path),
        ),
    ]
